# Generated by Django 6.0.1 on 2026-01-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_contact_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(max_length=200),
        ),
    ]
