# Generated by Django 6.0.1 on 2026-01-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_full_name_donation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='created_at',
            new_name='donated_at',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(max_length=100),
        ),
    ]
