# Generated by Django 6.0.1 on 2026-01-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_created_at_donation_donated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='loginactivity',
            old_name='login_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donation_type',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='loginactivity',
            name='password',
        ),
    ]
